### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by andreaballerino** [jenstornell/kirby-panel-flags#1]
Hi Jens, thanks for this plugin :)
I don't see any image on panel:

![error](https://cloud.githubusercontent.com/assets/21194688/20641287/f1ba596e-b3f4-11e6-870e-8c35af0969ce.jpg)

I followed the instructions, but nothing appears.

Please, let me know.
Thanks.

**Comment by andreaballerino** [comment]
Problem solved, it was my computer :)

**Comment by jenstornell** [comment]
Sorry about the delay.

>Problem solved, it was my computer :)

I don't think so because we had a long discussion about it here:
https://forum.getkirby.com/t/issue-with-u-and-localhost-port/5873

I also added the issue here:
https://github.com/getkirby/kirby/issues/520

But if you are using the latest version on the development branch it might have fixed the problem. Did you?
